// CollatrEdge — config init command
// PRD refs: §7 Configuration, §18 Deployment, §22 Scenario 5, Appendix A

export type NetworkMode = "connected" | "local_network" | "standalone";

export interface ConfigInitOptions {
  output: string;
  mode: NetworkMode;
  force: boolean;
}

/**
 * Parse config init-specific args: --output/-o, --mode, --force.
 */
export function parseConfigInitArgs(args: string[]): ConfigInitOptions {
  let output = "./collatr-edge.toml";
  let mode: NetworkMode = "local_network";
  let force = false;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg === "--output" || arg === "-o") {
      const next = args[i + 1];
      if (next === undefined || next.startsWith("-")) {
        throw new Error("--output requires a file path argument");
      }
      output = next;
      i++;
    } else if (arg === "--mode") {
      const next = args[i + 1];
      if (
        next !== "connected" &&
        next !== "local_network" &&
        next !== "standalone"
      ) {
        throw new Error(
          `Invalid mode: ${next ?? "(missing)"}. Must be one of: connected, local_network, standalone`,
        );
      }
      mode = next;
      i++;
    } else if (arg === "--force") {
      force = true;
    }
  }

  return { output, mode, force };
}

// ---------------------------------------------------------------------------
// Config template generation
// ---------------------------------------------------------------------------

function generateHubSection(mode: NetworkMode): string {
  if (mode === "connected") {
    return `
# ---------------------------------------------------------------------------
# Hub Connection (Sparkplug B) — edit values for your environment
# ---------------------------------------------------------------------------
[agent.hub]
  group_id = "plant_floor"
  edge_node_id = "edge-01"
  broker = "mqtts://hub.collatr.com:8883"
  tls_cert = "@{secrets:hub_cert}"
  tls_key = "@{secrets:hub_key}"
`;
  }

  const note =
    mode === "standalone"
      ? "# Hub connection — not available in standalone mode"
      : "# Hub connection — uncomment and configure to enable Hub forwarding";

  return `
${note}
# [agent.hub]
#   group_id = "plant_floor"
#   edge_node_id = "edge-01"
#   broker = "mqtts://hub.collatr.com:8883"
#   tls_cert = "@{secrets:hub_cert}"
#   tls_key = "@{secrets:hub_key}"
`;
}

function generateNetworkPolicySection(mode: NetworkMode): string {
  switch (mode) {
    case "connected":
      return `
# ---------------------------------------------------------------------------
# Network Policy (connected — allows Hub and internet access)
# ---------------------------------------------------------------------------
[network_policy]
  mode = "connected"
`;

    case "local_network":
      return `
# ---------------------------------------------------------------------------
# Network Policy (local_network — local LAN only, no internet)
# ---------------------------------------------------------------------------
[network_policy]
  mode = "local_network"

# [network_policy.egress]
#   allow_dns = false
#   allow_mqtt_hub = false
#   allowed_hosts = ["192.168.1.200:8086"]

# [network_policy.ingress]
#   allow_local_webui = true
#   allow_local_api = true
#   allowed_cidrs = ["192.168.1.0/24"]
`;

    case "standalone":
      return `
# ---------------------------------------------------------------------------
# Network Policy (standalone — no network egress)
# ---------------------------------------------------------------------------
[network_policy]
  mode = "standalone"

# [network_policy.egress]
#   allow_dns = false
#   allow_mqtt_hub = false
#   allowed_hosts = []
`;
  }
}

export function generateConfigTemplate(mode: NetworkMode): string {
  return `# CollatrEdge Configuration
# Generated by: collatr-edge config init --mode ${mode}
# Documentation: https://docs.collatr.com/edge/configuration
#
# Edit this file to match your setup, then validate with:
#   collatr-edge config validate --config <this-file>

# ---------------------------------------------------------------------------
# Agent Settings
# ---------------------------------------------------------------------------
[agent]
  # Data collection interval (how often inputs gather data)
  interval = "10s"

  # Round collection times to the interval boundary
  round_interval = true

  # Random jitter added to collection (prevents thundering herd)
  collection_jitter = "0s"

  # Fixed offset from interval boundary
  collection_offset = "0s"

  # How often outputs flush buffered data
  flush_interval = "10s"

  # Random jitter added to flush interval
  flush_jitter = "0s"

  # Timestamp precision (ms, s, m, h)
  precision = "1ms"

  # Log level: debug, info, warn, error
  log_level = "info"

# Buffer settings (SQLite write-ahead log)
# [agent.buffer]
#   sync_mode = "normal"  # "normal" or "full" (PRAGMA synchronous)
${generateHubSection(mode)}${generateNetworkPolicySection(mode)}
# ---------------------------------------------------------------------------
# Global Tags — added to every metric from this agent
# ---------------------------------------------------------------------------
[global_tags]
  # Uncomment and set tags that apply to all data:
  # site = "factory_a"
  # area = "production"
  # line = "line_1"

# ---------------------------------------------------------------------------
# Inputs
# ---------------------------------------------------------------------------

# Internal self-monitoring metrics (recommended — always keep enabled)
[[inputs.internal]]
  collect_memstats = true

# --- Modbus TCP ---
# Uncomment and configure for PLC/gateway connections:
# [[inputs.modbus]]
#   alias = "plc_01"
#   controller = "tcp://192.168.1.100:502"
#   interval = "5s"
#   timeout = "3s"
#   byte_order = "ABCD"             # ABCD (big-endian), CDAB, BADC, DCBA
#   optimization = "batch"
#   max_batch_size = 125
#
#   [[inputs.modbus.registers]]
#     address = 100
#     name = "motor_speed"
#     type = "holding"
#     data_type = "float32"
#     scale = 0.01
#   [[inputs.modbus.registers]]
#     address = 102
#     name = "temperature"
#     type = "holding"
#     data_type = "float32"

# --- OPC-UA ---
# Uncomment and configure for OPC-UA server connections:
# [[inputs.opcua]]
#   alias = "opc_server_01"
#   endpoint = "opc.tcp://192.168.1.50:4840"
#   security_policy = "None"
#   security_mode = "None"
#
#   [[inputs.opcua.nodes]]
#     node_id = "ns=2;s=Temperature"
#     name = "temperature"
#   [[inputs.opcua.nodes]]
#     node_id = "ns=2;s=Pressure"
#     name = "pressure"

# ---------------------------------------------------------------------------
# Processors
# ---------------------------------------------------------------------------

# --- Rename fields ---
# [[processors.rename]]
#   order = 1
#   [[processors.rename.replace]]
#     field = "old_name"
#     dest = "new_name"

# --- Filter metrics ---
# [[processors.filter]]
#   namepass = ["temperature_*", "pressure_*"]
#   namedrop = ["debug_*"]

# ---------------------------------------------------------------------------
# Aggregators
# ---------------------------------------------------------------------------

# --- Basic statistics (mean, min, max, count) ---
# [[aggregators.basicstats]]
#   period = "60s"
#   drop_original = false
#   namepass = ["motor_speed", "temperature"]

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

# Local data store — persists metrics to SQLite
[outputs.local_store]
  path = "/var/collatr/data"
  retention_days = 90
  retention_max_gb = 10

# --- File output ---
# Uncomment to write metrics to a file (useful for debugging):
# [[outputs.file]]
#   path = "/var/log/collatr-edge/metrics.jsonl"
#   data_format = "json"

# --- Stdout output ---
# Uncomment to print metrics to stdout (useful for testing):
# [[outputs.stdout]]
#   data_format = "json"
`;
}

// ---------------------------------------------------------------------------
// Command implementation
// ---------------------------------------------------------------------------

/**
 * Generate a default TOML config file with comments.
 * Returns 0 on success, 1 on error.
 */
export async function configInitCommand(args: string[]): Promise<number> {
  let options: ConfigInitOptions;
  try {
    options = parseConfigInitArgs(args);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`Error: ${msg}\n`);
    return 1;
  }

  // Check if file already exists (unless --force)
  if (!options.force) {
    const file = Bun.file(options.output);
    if (await file.exists()) {
      process.stderr.write(
        `Error: File already exists: ${options.output}\nUse --force to overwrite.\n`,
      );
      return 1;
    }
  }

  const template = generateConfigTemplate(options.mode);

  try {
    await Bun.write(options.output, template);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`Error: Failed to write config file: ${msg}\n`);
    return 1;
  }

  process.stdout.write(
    `Generated default config at ${options.output}\n` +
      `Edit this file, then run:\n` +
      `  collatr-edge config validate --config ${options.output}\n` +
      `  collatr-edge run --config ${options.output}\n`,
  );
  return 0;
}
